app:
  name: "web_app"
  mode: "dev"
  port: 8082
  version: "v0.1.0"
  start_time: "2023-03-01"
  machine_id: 0

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "./logInfo/web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "mysql"
  dbname: "bluebell"
  page: 3
  size: 10
  max_open_conns: 200
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100